### PR TITLE
Update Travis configuration

### PR DESCRIPTION
**Pull request by ctrueden**
This externalizes the Travis build to make it easier to make blanket improvements to the SciJava build process.

### CODE REVIEW

**Comment by ctrueden** [comment]
@axtimwalde I updated this branch to reflect the latest Travis configuration as created by `travisify.sh` in `scijava/scijava-scripts`. It does not include the GPG signing, because I don't have permission to add the GPG key and iv variables to the repository.

This should be good to merge any time.

**Comment by ctrueden** [comment]
Someone please merge this. @axtimwalde @hanslovsky @bogovicj

**Comment by hanslovsky** [comment]
> I updated this branch to reflect the latest Travis configuration as created by travisify.sh in scijava/scijava-scripts. It does not include the GPG signing, because I don't have permission to add the GPG key and iv variables to the repository.

Do I need to add GPG signing before merging (and if yes, can you point me to instructions)?

**Comment by ctrueden** [comment]
Nah, don't worry about it for now. The GPG credentials are only used when releasing the component to OSS Sonatype. If you want to do that with this library in the future, we can add the GPG credentials then. Thanks @hanslovsky !

**Pull request merged**
